### ISSUE TITLE
Doesn't support v8.1

### ISSUE THREAD

**Issue by MisterAero** [ramikg/openwithida#1]
ida64.dll was not found
how do we manually set the IDA installation path?
only before installation?

**Comment by ramikg** [comment]
> ida64.dll was not found

What action triggered this error?  
Also, which version of IDA are you using? I've tested on IDA Pro 8.1 and haven't noticed anything wrong.

> how do we manually set the IDA installation path? only before installation?

You can manually set the IDA installation path only after installing _OpenWithIDA_.

To do so:

1. Locate _OpenWithIDA_'s `installer.py`. The exact location will depend on your Python environment, but you can use software such as [_Everything_](https://www.voidtools.com/) to quickly find it.
2. Run `py installer.py --ida-folder <IDA_FOLDER>`, where _IDA_FOLDER_ is some valid IDA installation path.
