### ISSUE TITLE
i tried to install but it failed

### ISSUE THREAD

**Issue by ricnar456** [ramikg/openwithida#2]
i tried to install but it falis

C:\Users\admin\Downloads\openwithida-master\openwithida-master>pip -v install openwithida
Collecting openwithida
  1 location(s) to search for versions of openwithida:
  * https://pypi.python.org/simple/openwithida/
  Getting page https://pypi.python.org/simple/openwithida/
  Looking up "https://pypi.python.org/simple/openwithida/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org

C:\Users\admin\Downloads\openwithida-master\openwithida-master>

when I executed the installer

C:\Users\admin\Downloads\openwithida-master\openwithida-master\openwithida>py installer.py --ida-folder C:\Program Files\IDA Pro 8.4
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\openwithida-master\openwithida-master\openwithida\installer.py", line 17, in <module>
    from openwithida import common
ModuleNotFoundError: No module named 'openwithida'

C:\Users\admin\Downloads\openwithida-master\openwithida-master\openwithida>py installer.py --ida-folder C:\Program Files\IDA Pro 8.4
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\openwithida-master\openwithida-master\openwithida\installer.py", line 17, in <module>
    from openwithida import common
ModuleNotFoundError: No module named 'openwithida'

**Comment by ramikg** [comment]
Seems to be a _pip_ issue. Does `pip install` work for other packages?

In any case, since you've already downloaded the repository, `pip install .` should also work.  
(Or `pip install -e .` if you want to keep the `openwithida-master` folder.)

**Comment by ricnar456** [comment]
yes it was an old pip version fault with https, i use a newer version and it worked, thanks
